import {freeMathsResources} from './free-maths.mjs';
// Science checked 27 September; free maths checked 3 October 2026.
export const revisionResources = [
 ...freeMathsResources,
 {id:'light',subject:'science',title:'Light & shadows: explain what changes',provider:'MCQ.SG',url:'https://mcq.sg/science-mcq/light',topics:'Light (P4)',focus:'Use diagrams to reason about shadows and how light reaches our eyes.',access:'Public practice questions with answer checks; extra features may require an account.',difficulty:'Diagram reasoning',task:'Complete the public questions. For two answers, explain why your chosen option is correct and why one other option is wrong.'},
 {id:'heat',subject:'science',title:'Heat: compare experimental setups',provider:'MCQ.SG',url:'https://mcq.sg/science-mcq/heat-and-temperature',topics:'Heat (P4) · Materials',focus:'Compare heat transfer in different setups and apply ideas about conductors.',access:'Public practice questions with answer checks; extra features may require an account.',difficulty:'Application',task:'Complete the public questions. Choose one experimental setup and explain the direction of heat transfer.'},
 {id:'matter',subject:'science',title:'Matter: use evidence to decide',provider:'MCQ.SG',url:'https://mcq.sg/science-mcq/matter',topics:'Matter (P4)',focus:'Apply ideas about mass, volume and the properties of solids, liquids and gases.',access:'Public practice questions with answer checks; extra features may require an account.',difficulty:'Application',task:'Complete the public questions and explain two answers using the words mass, volume, shape or space where appropriate.'},
 {id:'magnets',subject:'science',title:'Magnets: attraction or repulsion?',provider:'MCQ.SG',url:'https://mcq.sg/science-mcq/magnets',topics:'Magnets (P3) · Materials',focus:'Reason about magnetic materials and poles. Skip electromagnet extensions beyond the supplied scope.',access:'Public practice questions with answer checks; extra features may require an account.',difficulty:'Reasoning',task:'Try the questions about magnetic materials and poles. Explain what repulsion tells you about two objects.'}
];
