// Provider pages checked 27 September 2026. Links, not copied third-party question banks.
export const revisionResources = [
 {id:'math-word-problems',subject:'maths',title:'Multi-step Maths practice',provider:'Home Campus',url:'https://my.homecampus.com.sg/Practice/Primary_4_Mathematics',topics:'Whole numbers · Fractions · Decimals · Area & perimeter',focus:'Choose Word Problems under whole numbers, fractions or decimals, or Composite Figures under measurement. Show every step of your working.',access:'Topic practice index; a provider account or subscription may be required.',difficulty:'Problem solving',task:'Complete 5 word problems or composite-figure questions. Show your working on paper and explain one question you found difficult to your tutor.'},
 {id:'decimal-word-problems',subject:'maths',title:'Decimals in word problems',provider:'IXL Singapore',url:'https://sg.ixl.com/maths/primary-4/add-and-subtract-decimals-word-problems',topics:'Decimals · Addition & subtraction · Problem solving',focus:'Translate a word problem into calculations, keeping decimal places aligned.',access:'Limited practice may be available; continued practice may require a subscription.',difficulty:'Application',task:'Try 5 questions, or as many as the free access allows. Record your working and any questions you want to review.'},
 {id:'light',subject:'science',title:'Light & shadows: explain what changes',provider:'MCQ.SG',url:'https://mcq.sg/science-mcq/light',topics:'Light (P4)',focus:'Use diagrams to reason about shadows and how light reaches our eyes.',access:'Public practice questions with answer checks; extra features may require an account.',difficulty:'Diagram reasoning',task:'Complete the public questions. For two answers, explain why your chosen option is correct and why one other option is wrong.'},
 {id:'heat',subject:'science',title:'Heat: compare experimental setups',provider:'MCQ.SG',url:'https://mcq.sg/science-mcq/heat-and-temperature',topics:'Heat (P4) · Materials',focus:'Compare heat transfer in different setups and apply ideas about conductors.',access:'Public practice questions with answer checks; extra features may require an account.',difficulty:'Application',task:'Complete the public questions. Choose one experimental setup and explain the direction of heat transfer.'},
 {id:'matter',subject:'science',title:'Matter: use evidence to decide',provider:'MCQ.SG',url:'https://mcq.sg/science-mcq/matter',topics:'Matter (P4)',focus:'Apply ideas about mass, volume and the properties of solids, liquids and gases.',access:'Public practice questions with answer checks; extra features may require an account.',difficulty:'Application',task:'Complete the public questions and explain two answers using the words mass, volume, shape or space where appropriate.'},
 {id:'magnets',subject:'science',title:'Magnets: attraction or repulsion?',provider:'MCQ.SG',url:'https://mcq.sg/science-mcq/magnets',topics:'Magnets (P3) · Materials',focus:'Reason about magnetic materials and poles. Skip electromagnet extensions beyond the supplied scope.',access:'Public practice questions with answer checks; extra features may require an account.',difficulty:'Reasoning',task:'Try the questions about magnetic materials and poles. Explain what repulsion tells you about two objects.'}
];
